### ISSUE TITLE
Remove Docker references

### ISSUE THREAD

**Issue by stephendonner** [mozilla-services/axe-selenium-python#131]
We should update (remove) Docker-specific instructions and references, from at least here: https://github.com/mozilla-services/axe-selenium-python/blob/22a6e1e09a19b282b40729d81cec475c1baeb371/README.rst#contributing

**Comment by kimberlythegeek** [comment]
Good catch. thanks @stephendonner

**Comment by kimberlythegeek** [comment]
closing in favor of #136
