### ISSUE TITLE
Add a test_write_results_without_filepath

### ISSUE THREAD

**Issue by kimberlythegeek** [mozilla-services/axe-selenium-python#159]
Should add a test to verify that `write_results` still works when no file name or path is given

**Comment by kimberlythegeek** [comment]
@terrameijar This occurred to me when reviewing your pr; feel free to pick this up if desired

**Comment by terrameijar** [comment]
@kimberlythegeek Thanks! On it.

**Comment by terrameijar** [comment]
I noticed that the `test_write_results_to_file()` test writes results data to a JSON file that doesn't get deleted at the end of the test. I think this file should be deleted after the test run is over. We can use the `tempfile` module to take care of removing the file after it has been read and the test is over. What do you think @kimberlythegeek ?

**Comment by kimberlythegeek** [comment]
@terrameijar Great idea! I hadn't thought of that :)

**Comment by hzk120** [comment]
@kimberlythegeek Is this issue still open?, I would like to work on it if thats the case.

**Comment by kimberlythegeek** [comment]
apologies, @hzk120 , looks like this was fixed in #163
