### ISSUE TITLE
Find a way to parametrize the tests using a rules list

### ISSUE THREAD

**Issue by kimberlythegeek** [mozilla-services/axe-selenium-python#45]
How do we programmatically generate tests for each rule
AND enable customization of the rule set to test
AND allow ability to xfail
AND maintain a simplicity of use

Current problem is that `parametrize` is a decorator, which gets executed *before* the function call.

**Comment by jrbenny35** [comment]
Could you explain how a test case would work?

**Comment by kimberlythegeek** [comment]
@jrbenny35 So this is something I was working on for a while during the internship. I'm not sure if this is still a priority. At the time, I was executing aXe against the page, storing the violations, and checking to see if an entry with each `ruleId` existed.

In most cases, I'm not sure we will want an individual test for each accessibility rule. @m8ttyB thoughts?

**Comment by m8ttyB** [comment]
@kimberlythegeek let's add this to our list of things to discuss during our hackathon this week. I'm not sure if this is needed.

**Comment by kimberlythegeek** [comment]
@m8ttyB I'm going to go ahead and close this for now. We'll likely continue without it.
