### ISSUE TITLE
Add option to specify external rules file

### ISSUE THREAD

**Issue by m8ttyB** [mozilla-services/axe-selenium-python#46]
To allow for a diversity of configuration options, add an option to specify and use an external file containing a list of rules to run checks against.

As a first pass, let's use `--rules` as the command-line specifier.

**Comment by kimberlythegeek** [comment]
Along the lines of #45 , I'm not sure this is needed. Deque does a good job of both coverage and configuration options in the aXe API.

@m8ttyB thoughts?

**Comment by m8ttyB** [comment]
Yes, close it! Our knowledge and understanding has come a long way has come a long way since August.

**Comment by kimberlythegeek** [comment]
It has indeed :)
